Лабораторна робота 1.
Вступ до машинного навчання.
Елементи лінійної алгебри.
Виконала:
Студентка ФІТ 4-9
Фесюк Олеся


https://github.com/Olllesssyya/Machinelearning/

In [2]:
import numpy as np
np.__version__

'2.0.2'

1. Створіть одновимірний масив (вектор) зі значеннями n! кожного натурального числа n, починаючи з 1, та виведіть його значення.

In [15]:
count = 10
n_values = np.arange(1, count + 1)
factorial_array = np.cumprod(n_values)
print(f"Вектор: {factorial_array}")

Вектор: [      1       2       6      24     120     720    5040   40320  362880
 3628800]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими значеннями косинусів кожного натурального числа, починаючи з 1, та виведіть його значення.

In [21]:
n_values = np.arange(1, 10)
inv_cos = 1 / np.cos(n_values)
matrix = inv_cos.reshape((3, 3))
print(f"Матриця 3x3 з оберненими значеннями косинусів від 1 до 9: \n {matrix}")


Матриця 3x3 з оберненими значеннями косинусів від 1 до 9: 
 [[ 1.85081572 -2.40299796 -1.01010867]
 [-1.52988566  3.52532009  1.04148193]
 [ 1.3264319  -6.87285064 -1.09753791]]


3. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до 1 та знайдіть відсоток чисел, які менше нуля.

In [22]:
matrix = np.random.uniform(-1, 1, (3, 3))
neg_count = np.sum(matrix < 0)
total = matrix.size
percent_neg = (neg_count / total) * 100

print("Згенерована матриця:")
print(matrix)
print(f"Відсоток чисел менших за нуль: {percent_neg:.2f}%")

Згенерована матриця:
[[ 0.19829651 -0.34267983 -0.07927027]
 [-0.55306215 -0.5106485   0.16270144]
 [-0.64014767 -0.97044633  0.43807966]]
Відсоток чисел менших за нуль: 66.67%


4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1.4 до 1.4 та виведіть його значення.

In [25]:
matrix = np.random.uniform(-1.4, 1.4, (3, 3))
print(f"Матриця 3x3 з випадковими числами від -1.4 до 1.4: \n {matrix}")


Матриця 3x3 з випадковими числами від -1.4 до 1.4: 
 [[ 1.33151724  1.00272744  1.16982737]
 [-0.70698028 -1.00899294  0.53294299]
 [ 0.75990841  1.20783097 -0.14937502]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 2 до 7 та виконайте на них поелементні операції додавання, віднімання та множення.

In [26]:
array1 = np.random.randint(2, 8, size=5)
array2 = np.random.randint(2, 8, size=5)

sum_result = array1 + array2
diff_result = array1 - array2
prod_result = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("Сума:", sum_result)
print("Різниця:", diff_result)
print("Добуток:", prod_result)


Масив 1: [5 2 6 7 3]
Масив 2: [4 5 5 2 3]
Сума: [ 9  7 11  9  6]
Різниця: [ 1 -3  1  5  0]
Добуток: [20 10 30 14  9]


6.Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 3 до 13 та знайдіть їх добуток.

In [27]:
import numpy as np
matrix1 = np.random.randint(3, 14, size=(4, 4))
matrix2 = np.random.randint(3, 14, size=(4, 4))

dobutok_matrix = np.dot(matrix1, matrix2)

print(f"Матриця 1: \n {matrix1}")
print(f"\nМатриця 2: \n {matrix1}")
print(f"\nДобуток матриць: \n {dobutok_matrix}")


Матриця 1: 
 [[11  3  6  7]
 [ 7  6  9  4]
 [11 11  5 13]
 [10  8  9 11]]

Матриця 2: 
 [[11  3  6  7]
 [ 7  6  9  4]
 [11 11  5 13]
 [10  8  9 11]]

Добуток матриць: 
 [[270 257 155 195]
 [219 227 143 185]
 [367 336 273 348]
 [347 329 243 308]]


7.Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.

In [29]:
matrix1 = np.random.randint(1, 5, size=(2, 3))
matrix2 = np.random.randint(1, 5, size=(3, 4))
dobutok_matrix = np.dot(matrix1, matrix2)

print(f"Матриця A (2x3): \n {matrix1}")
print(f"\nМатриця B (3x4): \n {matrix2}")
print(f"\nДобуток матриць (2x4): \n {dobutok_matrix}")


Матриця A (2x3): 
 [[1 2 3]
 [3 3 2]]

Матриця B (3x4): 
 [[4 4 2 1]
 [4 4 1 1]
 [3 1 2 4]]

Добуток матриць (2x4): 
 [[21 15 10 15]
 [30 26 13 14]]


8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [32]:
matrix = np.random.randint(1, 16, size=(3, 3))

inverse_matrix = np.linalg.inv(matrix)

print(f"Матриця 3x3:\n {matrix}")
print(f"\nОбернена матриця: \n{inverse_matrix}")


Матриця 3x3:
 [[11  8 14]
 [10  3  9]
 [ 9  1  3]]

Обернена матриця: 
[[ 4.03717464e-17 -5.88235294e-02  1.76470588e-01]
 [ 3.00000000e-01 -5.47058824e-01  2.41176471e-01]
 [-1.00000000e-01  3.58823529e-01 -2.76470588e-01]]


9.Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від 0 до 10 та транспонуйте її.

In [36]:
import numpy as np

matrix = np.random.uniform(0, 10, size=(7, 7))
transposed_matrix = np.transpose(matrix)

print("Матриця 7x7:")
print(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)


Матриця 7x7:
[[3.74688662 7.63420256 5.95352699 5.91289732 8.33786896 8.25862985
  2.23002201]
 [7.25226939 6.80251355 3.38165136 7.81857498 8.35102556 1.16167305
  4.65067949]
 [0.09140169 1.71651911 0.16735362 5.09282723 3.48771324 0.78902122
  5.16247453]
 [4.15839073 6.49373057 7.28147078 5.73971026 9.74829844 5.83756382
  7.14957343]
 [0.58984829 8.85220817 0.6905913  7.44651496 1.06325202 0.56991395
  9.42818453]
 [4.03882925 5.29965756 7.44832962 9.41675139 4.21980978 6.97544775
  9.83356088]
 [6.96537595 4.15587839 4.77050443 2.09086544 5.12796732 1.54307482
  9.68061141]]

Транспонована матриця:
[[3.74688662 7.25226939 0.09140169 4.15839073 0.58984829 4.03882925
  6.96537595]
 [7.63420256 6.80251355 1.71651911 6.49373057 8.85220817 5.29965756
  4.15587839]
 [5.95352699 3.38165136 0.16735362 7.28147078 0.6905913  7.44832962
  4.77050443]
 [5.91289732 7.81857498 5.09282723 5.73971026 7.44651496 9.41675139
  2.09086544]
 [8.33786896 8.35102556 3.48771324 9.74829844 1.06325202 4.2

10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [37]:
matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, size=(4, 1))

dobutok = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)

print("\nВектор 4x1:")
print(vector)

print("\nДобуток матриці на вектор:")
print(dobutok)


Матриця 3x4:
[[0.94690072 0.87061347 0.94380815 0.48362094]
 [0.42026197 0.08418378 0.77154711 0.11578384]
 [0.83722796 0.06262935 0.46746469 0.13863149]]

Вектор 4x1:
[[3]
 [3]
 [5]
 [5]]

Добуток матриці на вектор:
[[12.58968804]
 [ 5.949992  ]
 [ 5.73005279]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [38]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3, 1)

dobutok = np.dot(matrix, vector)

print("Матриця 2x3:")
print(matrix)

print("\nВектор 3x1:")
print(vector)

print("\nДобуток матриці на вектор:")
print(dobutok)

Матриця 2x3:
[[0.78036104 0.09515587 0.7985093 ]
 [0.30207628 0.31073452 0.2962413 ]]

Вектор 3x1:
[[0.11485152]
 [0.65362521]
 [0.29734493]]

Добуток матриці на вектор:
[[0.38925462]
 [0.32588369]]


12. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та знайдіть різницю елементів першої і другої матриць.

In [39]:
matrix1 = np.random.randint(1, 4, size=(3, 3))
matrix2 = np.random.randint(1, 4, size=(3, 3))

difference = matrix1 - matrix2

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

print("\nРізниця матриць:")
print(difference)


Матриця 1:
[[2 3 2]
 [1 1 3]
 [2 3 2]]

Матриця 2:
[[2 3 1]
 [1 2 3]
 [3 3 1]]

Різниця матриць:
[[ 0  0  1]
 [ 0 -1  0]
 [-1  0  1]]


13.Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть добуток їх елементів.

In [40]:
matrix1 = np.random.randint(1, 6, (3, 3))
matrix2 = np.random.randint(1, 6, (3, 3))

dobutok = np.prod(matrix1) * np.prod(matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Добуток елементів обох матриць:", dobutok)


Matrix 1:
 [[2 3 2]
 [5 1 3]
 [5 2 3]]
Matrix 2:
 [[4 2 2]
 [3 5 2]
 [3 1 3]]
Добуток елементів обох матриць: 23328000


14.Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів на побічній діагоналі.

In [41]:
matrix = np.random.randint(1, 101, (4, 4))
sum = np.trace(np.fliplr(matrix))

print("Matrix:\n", matrix)
print("Сума елементів на побічній діагоналі:", sum)


Matrix:
 [[46 82 27 32]
 [53 43 55 43]
 [34 83 40  8]
 [12 68 85 85]]
Сума елементів на побічній діагоналі: 182


15.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем значення елементу у кожному стовпці матриці.

In [42]:
matrix = np.random.uniform(-2, 2, (3, 3))
idx = np.argmin(np.abs(matrix), axis=0)
vector = matrix[idx, np.arange(matrix.shape[1])].reshape(-1, 1)

print("Matrix:\n", matrix)
print("Вектор-стовпчик найменших за модулем елементів кожного стовпця:\n", vector)


Matrix:
 [[ 0.83762967  0.26076657 -1.25194101]
 [ 0.5760318   1.39041953  1.19948275]
 [ 0.25323894 -1.92756512  1.10621684]]
Вектор-стовпчик найменших за модулем елементів кожного стовпця:
 [[0.25323894]
 [0.26076657]
 [1.10621684]]


Висновки:розглянули бібліотеку NumPy та її можливості. З’ясували, що вона дозволяє швидко створювати матриці й вектори. Виконання специфічних операцій над матрицями та векторами за допомогою цієї бібліотеки не займає багато часу на написання коду й суттєво спрощує процес обробки даних.